title = "Configuration"

[info]
kernel = true
hostname = true
type_ = true
uptime = true
cpu = true
gpu = false
local_ip = false
used_memory = true
total_memory = true

[ascii]
distro = "default"
size = "default"